//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MabiCooker2.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MabiCooker2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Close_hover {
            get {
                object obj = ResourceManager.GetObject("Close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Detail {
            get {
                object obj = ResourceManager.GetObject("Detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Favorite {
            get {
                object obj = ResourceManager.GetObject("Favorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Favorite_hover {
            get {
                object obj = ResourceManager.GetObject("Favorite_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap FavoriteRemove {
            get {
                object obj = ResourceManager.GetObject("FavoriteRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap FavoriteRemove_hover {
            get {
                object obj = ResourceManager.GetObject("FavoriteRemove_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   cook.dat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileCookData {
            get {
                return ResourceManager.GetString("FileCookData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CookData.xml과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileCookDataXml {
            get {
                return ResourceManager.GetString("FileCookDataXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   favcook.dat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileFavoriteData {
            get {
                return ResourceManager.GetString("FileFavoriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stuff.dat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileStuffData {
            get {
                return ResourceManager.GetString("FileStuffData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon Icon2 {
            get {
                object obj = ResourceManager.GetObject("Icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   즐겨찾기가 삭제됩니다.
        ///정말 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgConfirm {
            get {
                return ResourceManager.GetString("MsgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   favcook.dat 파일을 다른 프로그램에서 사용하고 있습니다.
        ///즐겨찾기 목록이 저장되지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailure {
            get {
                return ResourceManager.GetString("MsgFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기에 추가 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFavoriteAdd {
            get {
                return ResourceManager.GetString("MsgFavoriteAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기에서 삭제 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFavoriteRemove {
            get {
                return ResourceManager.GetString("MsgFavoriteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 파일이 존재하지 않습니다.
        ///확인 해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNoDataFile {
            get {
                return ResourceManager.GetString("MsgNoDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Ratio {
            get {
                object obj = ResourceManager.GetObject("Ratio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   이전 요리 보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrBack {
            get {
                return ResourceManager.GetString("StrBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (조리불가)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCannotCook {
            get {
                return ResourceManager.GetString("StrCannotCook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비율보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDisplayRatio {
            get {
                return ResourceManager.GetString("StrDisplayRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFavorite {
            get {
                return ResourceManager.GetString("StrFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   즐겨찾기 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFavoriteRemove {
            get {
                return ResourceManager.GetString("StrFavoriteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNotice {
            get {
                return ResourceManager.GetString("StrNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWarning {
            get {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }
    }
}
